<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
	<title><?php $this->output($title);?>应用详情</title>
	<link rel="stylesheet" href="/static/css/weui.min.css"/>
	<link rel="stylesheet" href="/static/style.css"/>
</head>
<body ontouchstart>
<div class="weui-toptips weui-toptips_warn js_tooltips">错误提示</div>

<div class="container" id="container"></div>

<script type="text/html" id="tpl_home">
	<div class="page">
		<div class="page__hd">
			<h1 class="page__title">应用</h1>
			<p class="page__desc">文章</p>
		</div>
		<div class="page__bd">
			<article class="weui-article">
				<h1>大标题</h1>
				<section>
					<h2 class="title">章标题</h2>
					<section>
						<h3>1.1 节标题</h3>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
							consequat.
						</p>
						<p>
							<img src="/static/images/pic_article.png" alt="">
							<img src="/static/images/pic_article.png" alt="">
						</p>
					</section>
					<section>
						<h3>1.2 节标题</h3>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
						</p>
					</section>
				</section>
			</article>
		</div>
		<div class="page__ft">

			<div class="weui-footer">
				<p class="weui-footer__links">
					<a href="javascript:void(0);" class="weui-footer__link">底部链接</a>
					<a href="/page/detail.html" class="weui-footer__link">详情</a>
				</p>
				<p class="weui-footer__text">Copyright &copy; 2008-2016 万铺后端云</p>
			</div>
		</div>
	</div>
</script>


<script src="/static/js/zepto.min.js"></script>
<script type="text/javascript" src="https://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
<script src="/static/js/app.js"></script>

<script type="text/javascript">
	$(function(){
		var winH = $(window).height();
		var categorySpace = 10;

		$('.js_item').on('click', function(){
			var id = $(this).data('id');
			window.pageManager.go(id);
		});
		$('.js_category').on('click', function(){
			var $this = $(this),
				$inner = $this.next('.js_categoryInner'),
				$page = $this.parents('.page'),
				$parent = $(this).parent('li');
			var innerH = $inner.data('height');
			bear = $page;

			if(!innerH){
				$inner.css('height', 'auto');
				innerH = $inner.height();
				$inner.removeAttr('style');
				$inner.data('height', innerH);
			}

			if($parent.hasClass('js_show')){
				$parent.removeClass('js_show');
			}else{
				$parent.siblings().removeClass('js_show');

				$parent.addClass('js_show');
				if(this.offsetTop + this.offsetHeight + innerH > $page.scrollTop() + winH){
					var scrollTop = this.offsetTop + this.offsetHeight + innerH - winH + categorySpace;

					if(scrollTop > this.offsetTop){
						scrollTop = this.offsetTop - categorySpace;
					}

					$page.scrollTop(scrollTop);
				}
			}
		});
	});
</script>
</body>
</html>
