<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
	<title><?php $this->output($title);?>应用列表</title>
	<link rel="stylesheet" href="/static/css/weui.min.css"/>
	<link rel="stylesheet" href="/static/style.css"/>
</head>
<body ontouchstart>
<div class="weui-toptips weui-toptips_warn js_tooltips">错误提示</div>

<div class="container" id="container"></div>

<script type="text/html" id="tpl_home">
	<div class="page">
		<div class="page__hd">
			<h1 class="page__title">小应用列表</h1>
			<p class="page__desc">列表</p>
		</div>
		<div class="page__bd">
			<div class="weui-cells__title">带说明的列表项</div>
			<div class="weui-cells">
				<div class="weui-cell">
					<div class="weui-cell__bd">
						<p>标题文字</p>
					</div>
					<div class="weui-cell__ft">说明文字</div>
				</div>
			</div>
			<div class="weui-cells__title">带图标、说明的列表项</div>
			<div class="weui-cells">
				<div class="weui-cell">
					<div class="weui-cell__hd"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAC4AAAAuCAMAAABgZ9sFAAAAVFBMVEXx8fHMzMzr6+vn5+fv7+/t7e3d3d2+vr7W1tbHx8eysrKdnZ3p6enk5OTR0dG7u7u3t7ejo6PY2Njh4eHf39/T09PExMSvr6+goKCqqqqnp6e4uLgcLY/OAAAAnklEQVRIx+3RSRLDIAxE0QYhAbGZPNu5/z0zrXHiqiz5W72FqhqtVuuXAl3iOV7iPV/iSsAqZa9BS7YOmMXnNNX4TWGxRMn3R6SxRNgy0bzXOW8EBO8SAClsPdB3psqlvG+Lw7ONXg/pTld52BjgSSkA3PV2OOemjIDcZQWgVvONw60q7sIpR38EnHPSMDQ4MjDjLPozhAkGrVbr/z0ANjAF4AcbXmYAAAAASUVORK5CYII=" alt="" style="width:20px;margin-right:5px;display:block"></div>
					<div class="weui-cell__bd">
						<p>标题文字</p>
					</div>
					<div class="weui-cell__ft">说明文字</div>
				</div>
				<div class="weui-cell">
					<div class="weui-cell__hd"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAC4AAAAuCAMAAABgZ9sFAAAAVFBMVEXx8fHMzMzr6+vn5+fv7+/t7e3d3d2+vr7W1tbHx8eysrKdnZ3p6enk5OTR0dG7u7u3t7ejo6PY2Njh4eHf39/T09PExMSvr6+goKCqqqqnp6e4uLgcLY/OAAAAnklEQVRIx+3RSRLDIAxE0QYhAbGZPNu5/z0zrXHiqiz5W72FqhqtVuuXAl3iOV7iPV/iSsAqZa9BS7YOmMXnNNX4TWGxRMn3R6SxRNgy0bzXOW8EBO8SAClsPdB3psqlvG+Lw7ONXg/pTld52BjgSSkA3PV2OOemjIDcZQWgVvONw60q7sIpR38EnHPSMDQ4MjDjLPozhAkGrVbr/z0ANjAF4AcbXmYAAAAASUVORK5CYII=" alt="" style="width:20px;margin-right:5px;display:block"></div>
					<div class="weui-cell__bd">
						<p>标题文字</p>
					</div>
					<div class="weui-cell__ft">说明文字</div>
				</div>
			</div>

			<div class="weui-cells__title">带跳转的列表项</div>
			<div class="weui-cells">
				<a class="weui-cell weui-cell_access" href="javascript:;">
					<div class="weui-cell__bd">
						<p>cell standard</p>
					</div>
					<div class="weui-cell__ft">
					</div>
				</a>
				<a class="weui-cell weui-cell_access" href="javascript:;">
					<div class="weui-cell__bd">
						<p>cell standard</p>
					</div>
					<div class="weui-cell__ft">
					</div>
				</a>
			</div>

			<div class="weui-cells__title">带说明、跳转的列表项</div>
			<div class="weui-cells">
				<a class="weui-cell weui-cell_access" href="javascript:;">
					<div class="weui-cell__bd">
						<p>cell standard</p>
					</div>
					<div class="weui-cell__ft">说明文字</div>
				</a>
				<a class="weui-cell weui-cell_access" href="javascript:;">
					<div class="weui-cell__bd">
						<p>cell standard</p>
					</div>
					<div class="weui-cell__ft">说明文字</div>
				</a>

			</div>

			<div class="weui-cells__title">带图标、说明、跳转的列表项</div>
			<div class="weui-cells">

				<a class="weui-cell weui-cell_access" href="javascript:;">
					<div class="weui-cell__hd"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAC4AAAAuCAMAAABgZ9sFAAAAVFBMVEXx8fHMzMzr6+vn5+fv7+/t7e3d3d2+vr7W1tbHx8eysrKdnZ3p6enk5OTR0dG7u7u3t7ejo6PY2Njh4eHf39/T09PExMSvr6+goKCqqqqnp6e4uLgcLY/OAAAAnklEQVRIx+3RSRLDIAxE0QYhAbGZPNu5/z0zrXHiqiz5W72FqhqtVuuXAl3iOV7iPV/iSsAqZa9BS7YOmMXnNNX4TWGxRMn3R6SxRNgy0bzXOW8EBO8SAClsPdB3psqlvG+Lw7ONXg/pTld52BjgSSkA3PV2OOemjIDcZQWgVvONw60q7sIpR38EnHPSMDQ4MjDjLPozhAkGrVbr/z0ANjAF4AcbXmYAAAAASUVORK5CYII=" alt="" style="width:20px;margin-right:5px;display:block"></div>
					<div class="weui-cell__bd">
						<p>cell standard</p>
					</div>
					<div class="weui-cell__ft">说明文字</div>
				</a>
				<a class="weui-cell weui-cell_access" href="javascript:;">
					<div class="weui-cell__hd"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAC4AAAAuCAMAAABgZ9sFAAAAVFBMVEXx8fHMzMzr6+vn5+fv7+/t7e3d3d2+vr7W1tbHx8eysrKdnZ3p6enk5OTR0dG7u7u3t7ejo6PY2Njh4eHf39/T09PExMSvr6+goKCqqqqnp6e4uLgcLY/OAAAAnklEQVRIx+3RSRLDIAxE0QYhAbGZPNu5/z0zrXHiqiz5W72FqhqtVuuXAl3iOV7iPV/iSsAqZa9BS7YOmMXnNNX4TWGxRMn3R6SxRNgy0bzXOW8EBO8SAClsPdB3psqlvG+Lw7ONXg/pTld52BjgSSkA3PV2OOemjIDcZQWgVvONw60q7sIpR38EnHPSMDQ4MjDjLPozhAkGrVbr/z0ANjAF4AcbXmYAAAAASUVORK5CYII=" alt="" style="width:20px;margin-right:5px;display:block"></div>
					<div class="weui-cell__bd">
						<p>cell standard</p>
					</div>
					<div class="weui-cell__ft">说明文字</div>
				</a>
			</div>
		</div>
		<div class="page__ft">
			<a href="javascript:home()"><img src="./images/icon_footer_link.png" /></a>
		</div>
	</div>
</script>

<script src="/static/js/zepto.min.js"></script>
<script type="text/javascript" src="https://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
<script src="/static/js/app.js"></script>

<script type="text/javascript">
	$(function(){
		var winH = $(window).height();
		var categorySpace = 10;

		$('.js_item').on('click', function(){
			var id = $(this).data('id');
			window.pageManager.go(id);
		});
		$('.js_category').on('click', function(){
			var $this = $(this),
				$inner = $this.next('.js_categoryInner'),
				$page = $this.parents('.page'),
				$parent = $(this).parent('li');
			var innerH = $inner.data('height');
			bear = $page;

			if(!innerH){
				$inner.css('height', 'auto');
				innerH = $inner.height();
				$inner.removeAttr('style');
				$inner.data('height', innerH);
			}

			if($parent.hasClass('js_show')){
				$parent.removeClass('js_show');
			}else{
				$parent.siblings().removeClass('js_show');

				$parent.addClass('js_show');
				if(this.offsetTop + this.offsetHeight + innerH > $page.scrollTop() + winH){
					var scrollTop = this.offsetTop + this.offsetHeight + innerH - winH + categorySpace;

					if(scrollTop > this.offsetTop){
						scrollTop = this.offsetTop - categorySpace;
					}

					$page.scrollTop(scrollTop);
				}
			}
		});
	});
</script>
</body>
</html>
